### ISSUE TITLE
配置了ss后不能连接，VPN 还自动断开

### ISSUE THREAD

**Issue by samniu** [BurpSuite/UPlus-A.BIG.T#1]
同样使用surge的配置，就没问题，可以连接

**Comment by Heroic-Niu** [comment]
同样使用surge的配置，就没问题，可以连接

**Comment by burpsuite** [comment]
稍等我看一下

**Comment by burpsuite** [comment]
![img_0171](https://cloud.githubusercontent.com/assets/14309190/16296608/980924be-395f-11e6-9103-dd4cd3e67690.PNG)
![img_0173](https://cloud.githubusercontent.com/assets/14309190/16296610/9896c526-395f-11e6-82f7-52661f70965a.PNG)
![img_0172](https://cloud.githubusercontent.com/assets/14309190/16296609/984802c4-395f-11e6-8dda-e0dc1755acdc.PNG)

貌似没有问题呃....你再重新试试

**Comment by burpsuite** [comment]
会掉是因为A.BIG.T不稳定,你可以试试打开爱奇艺,看一会视频就掉了

**Comment by samniu** [comment]
我使用的是TestFlght 2.2.7 (Build 322)版本

**Comment by burpsuite** [comment]
![img_0174](https://cloud.githubusercontent.com/assets/14309190/16296895/d44274a2-3960-11e6-8256-0d9e48e1fbe0.PNG)
是的,我的也是

**Comment by samniu** [comment]
[A.BIG.T.TXT](https://github.com/BurpSuite/UPlus-A.BIG.T/files/329514/A.BIG.T.TXT)
您可以导入我的配置(上传改成TXT)试试看看吗？同样的ss账号，在surge上是可以的

**Comment by burpsuite** [comment]
好的,我重新下载一遍,导入你的,一会我再截图

**Comment by burpsuite** [comment]
![img_0176](https://cloud.githubusercontent.com/assets/14309190/16297269/ba42ab92-3962-11e6-91ff-0f1ea70c7721.PNG)
![img_0177](https://cloud.githubusercontent.com/assets/14309190/16297270/ba45f0ae-3962-11e6-85d7-9605fc950d74.PNG)
![img_0178](https://cloud.githubusercontent.com/assets/14309190/16297363/289e3a7a-3963-11e6-8f39-564f9d7de0f9.PNG)
![img_0179](https://cloud.githubusercontent.com/assets/14309190/16297361/263d827c-3963-11e6-8db9-308c5c028976.PNG)
我刚才重装了一遍,然后导入你的配置也是可以连接的呃...

**Comment by samniu** [comment]
谢谢！ 我再看看原因，删除A.BIG.T再试试.

**Comment by burpsuite** [comment]
嗯呃
